scoreboard players operation #now map_state = #stage map_state
execute if score #now map_state matches 1 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_01
execute if score #now map_state matches 1 run scoreboard players set #stage map_state 2
execute if score #now map_state matches 2 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_02
execute if score #now map_state matches 2 run scoreboard players set #stage map_state 3
execute if score #now map_state matches 3 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_03
execute if score #now map_state matches 3 run scoreboard players set #stage map_state 4
execute if score #now map_state matches 4 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_04
execute if score #now map_state matches 4 run scoreboard players set #stage map_state 5
execute if score #now map_state matches 5 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_05
execute if score #now map_state matches 5 run scoreboard players set #stage map_state 6
execute if score #now map_state matches 6 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_06
execute if score #now map_state matches 6 run scoreboard players set #stage map_state 7
execute if score #now map_state matches 7 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_07
execute if score #now map_state matches 7 run scoreboard players set #stage map_state 8
execute if score #now map_state matches 8 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_08
execute if score #now map_state matches 8 run scoreboard players set #stage map_state 9
execute if score #now map_state matches 9 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_09
execute if score #now map_state matches 9 run scoreboard players set #stage map_state 10
execute if score #now map_state matches 10 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_10
execute if score #now map_state matches 10 run scoreboard players set #stage map_state 11
execute if score #now map_state matches 11 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_11
execute if score #now map_state matches 11 run scoreboard players set #stage map_state 12
execute if score #now map_state matches 12 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_12
execute if score #now map_state matches 12 run scoreboard players set #stage map_state 13
execute if score #now map_state matches 13 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_13
execute if score #now map_state matches 13 run scoreboard players set #stage map_state 14
execute if score #now map_state matches 14 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_14
execute if score #now map_state matches 14 run scoreboard players set #stage map_state 15
execute if score #now map_state matches 15 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_15
execute if score #now map_state matches 15 run scoreboard players set #stage map_state 16
execute if score #now map_state matches 16 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_16
execute if score #now map_state matches 16 run scoreboard players set #stage map_state 17
execute if score #now map_state matches 17 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_17
execute if score #now map_state matches 17 run scoreboard players set #stage map_state 18
execute if score #now map_state matches 18 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_18
execute if score #now map_state matches 18 run scoreboard players set #stage map_state 19
execute if score #now map_state matches 19 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_19
execute if score #now map_state matches 19 run scoreboard players set #stage map_state 20
execute if score #now map_state matches 20 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_20
execute if score #now map_state matches 20 run scoreboard players set #stage map_state 21
execute if score #now map_state matches 21 as @e[type=armor_stand,name="build_anchor",c=1] at @s run function basgiath/stage_21
execute if score #now map_state matches 21 run scoreboard players set #stage map_state 0
execute if score #now map_state matches 0 run function basgiath/live
